# Generated by Django 5.2 on 2025-04-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_note_wellnesscheckin_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='end_time',
            new_name='class_time_end',
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='start_time',
            new_name='class_time_start',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_day',
            field=models.CharField(default='Monday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='location',
            field=models.CharField(default='Main Campus', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WellnessCheckIn',
        ),
    ]
